
version: "3.9"  # Version of Docker Compose

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for database

  # Product Service
  product-service:
    image: your-dockerhub-username/product-service:latest
    container_name: product-service
    ports:
      - "3001:3000"  # Expose service on a custom port
    environment:
      DATABASE_URL: postgres://ecommerce_user:ecommerce_password@postgres:5432/ecommerce_db
    depends_on:
      - postgres  # Ensure database starts before this service

  # Cart Service
  cart-service:
    image: your-dockerhub-username/cart-service:latest
    container_name: cart-service
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgres://ecommerce_user:ecommerce_password@postgres:5432/ecommerce_db
    depends_on:
      - postgres

  # Order Service
  order-service:
    image: your-dockerhub-username/order-service:latest
    container_name: order-service
    ports:
      - "3003:3000"
    environment:
      DATABASE_URL: postgres://ecommerce_user:ecommerce_password@postgres:5432/ecommerce_db
    depends_on:
      - postgres

  # API Gateway
  api-gateway:
    image: your-dockerhub-username/api-gateway:latest
    container_name: api-gateway
    ports:
      - "3000:3000"  # Gateway accessible on localhost:3000
    depends_on:
      - product-service
      - cart-service
      - order-service

volumes:
  postgres_data:  # Persistent volume for database storage
