
version: "3.9" 

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  product-service:
    image: tim299/product-service
    container_name: product-service
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://ecommerce_user:ecommerce_password@postgres:5432/ecommerce_db
    depends_on:
      - postgres
    volumes:
      - ./product-service:/app  
    command: npm run dev


  cart-service:
    image: tim299/cart-service
    container_name: cart-service
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgres://ecommerce_user:ecommerce_password@postgres:5432/ecommerce_db
    depends_on:
      - postgres
    volumes:
      - ./cart-service:/app  

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

    environment:
      NODE_ENV: development

  order-service:
    image: tim299/order-service
    container_name: order-service
    ports:
      - "3003:3000"
    environment:
      DATABASE_URL: postgres://ecommerce_user:ecommerce_password@postgres:5432/ecommerce_db
    depends_on:
      - postgres
    volumes:
      - ./order-service:/app  


  api-gateway:
    image: tim299/api-gateway
    container_name: api-gateway
    ports:
      - "3004:3000"
    depends_on:
      - product-service
      - cart-service
      - order-service
    volumes:
      - ./api-gateway:/app  

volumes:
  postgres_data:
